# Generated by Django 3.2.5 on 2021-08-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenthicate', '0004_cafeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
