# Generated by Django 3.2.5 on 2021-08-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenthicate', '0005_alter_cafeprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeprofile',
            name='image',
        ),
    ]
