# Generated by Django 3.2.5 on 2021-08-01 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenthicate', '0007_auto_20210801_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cafeName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.CreateModel(
            name='CafeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafeName', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
